config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  authenticated :admin do
    root to: "admin#index", as: :admin_root
  end

  root "home#index"
  get "admin" => "admin#index"
  get "up" => "rails/health#show", as: :rails_health_check
  
  namespace :admin do
    resources :orders
    resources :categories
    resources :products do
      resources :stocks
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_products
  has_many :products, through: :order_products

  VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :customer_email, format: {with: VALID_EMAIL_REGEX}, allow_nil: true

  enum status: { pending: 0, placed: 1, shipped: 2, completed: 3, cancelled: 4 }
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < AdminController
  before_action :set_admin_order, only: %i[ show edit update destroy ]

  # GET /admin/orders or /admin/orders.json
  def index
    @incomplete_orders = Order.where.not(status: [:completed, :cancelled]).order(created_at: :asc)
    @completed_orders = Order.where(status: [:completed, :cancelled]).order(created_at: :asc)
  end

  # GET /admin/orders/1 or /admin/orders/1.json
  def show
  end

  # GET /admin/orders/new
  def new
    @admin_order = Order.new
  end

  # GET /admin/orders/1/edit
  def edit
  end

  # POST /admin/orders or /admin/orders.json
  def create
    @admin_order = Order.new(admin_order_params)

    respond_to do |format|
      if @admin_order.save
        format.html { redirect_to admin_order_url(@admin_order), notice: "Order was successfully created." }
        format.json { render :show, status: :created, location: @admin_order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @admin_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/orders/1 or /admin/orders/1.json
  def update
    respond_to do |format|
      if @admin_order.update(admin_order_params)
        format.html { redirect_to admin_order_url(@admin_order), notice: "Order was successfully updated." }
        format.json { render :show, status: :ok, location: @admin_order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @admin_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/orders/1 or /admin/orders/1.json
  def destroy
    @admin_order.destroy!

    respond_to do |format|
      format.html { redirect_to admin_orders_url, notice: "Order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_order
      @admin_order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def admin_order_params
      params.require(:order).permit(:customer_email, :status, :total, :address)
    end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/_form.html.erb
<%= form_with(model: [:admin, @admin_order], class: "contents") do |form| %>
  <% if @admin_order.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(@admin_order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% @admin_order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :customer_email %>
    <%= form.text_field :customer_email, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :status %>
    <%= form.collection_select :status, Order.statuses.keys, :to_s, :humanize, prompt: 'Select Status', class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :total %>
    <%= form.number_field :total, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :address %>
    <%= form.text_field :address, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/admin/orders/_order.html.erb
<div id="<%= dom_id order %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Customer email:</strong>
    <span class="ml-2">
      <%= order.customer_email %>
    <span>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Status:</strong>
    <span class="ml-2">
      <%= order.status %>
    <span>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Total:</strong>
    <span class="ml-2">
      <%= order.total %>
    <span>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Address:</strong>
    <span class="ml-2">
      <%= order.address %>
    </span>
  </p>

  <% if order.order_products.any? %>
    <p class="my-5">
      <strong class="block font-medium mb-1">Products:</strong>
      <% order.order_products.each_with_index do |order_product, index| %>
        <span class="mb-2 ml-2">
          <%= index + 1 %>.  
          <%= order_product.product.name %>
           of size <%= order_product.size %>
           and quantity <%= order_product.quantity %>
        </p>
      <% end %>
    </p>
  <% end %>

</div>

app/views/admin/orders/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing order</h1>

  <%= render "form", admin_order: @admin_order %>

  <%= link_to "Show this order", admin_order_path(@admin_order), class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to orders", admin_orders_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/admin/orders/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Orders" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Orders</h1>
    <%= link_to "New order", new_admin_order_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div class="flex flex-col w-full">
    <div class="overflow-x-auto sm:mx-0.5 lg:mx-0.5">
      <div class="py-2 inline-block min-w-full">
        <div class="overflow-x-auto">
          <h2 class="inline-block text-xl font-bold text-gray-500 py-2"> Incomplete Orders:</h2>
          <table class="min-w-full overflow-x-scroll">
            <thead class="bg-white border-b">
              <tr>
                <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">Order ID</th>
                <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">Customer email</th>
                <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">Status</th>
                <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">Total</th>
                <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">Address</th>
              </tr>
            </thead>
            <tbody class="bg-white divide-y divide-gray-200">
              <% @incomplete_orders.each do |admin_order| %>
                <tr class="bg-gray-50 border-b hover:bg-gray-100">
                  <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-800 cursor-pointer">
                    <%= link_to admin_order.id, [:admin, admin_order], class: 'underline' %>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-800 cursor-pointer" onclick="window.location='<%= admin_order_path(admin_order) %>'">
                    <%= admin_order.customer_email %>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-800 cursor-pointer" onclick="window.location='<%= admin_order_path(admin_order) %>'">
                    <%= admin_order.status %>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-800 cursor-pointer" onclick="window.location='<%= admin_order_path(admin_order) %>'">
                    <%= admin_order.total %>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-800 cursor-pointer" onclick="window.location='<%= admin_order_path(admin_order) %>'">
                    <%= admin_order.address %>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-800">
                    <%= link_to icon('fas', 'pen-to-square'), edit_admin_order_path(admin_order), class: "rounded-lg py-3 px-3 bg-blue-600 text-white inline-block font-medium" %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>

        <div class="overflow-x-auto">
          <h2 class="inline-block text-xl font-bold text-gray-500 py-2 mt-4"> Completed Orders:</h2>
          <table class="min-w-full overflow-x-scroll">
            <thead class="bg-white border-b">
              <tr>
                <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">Order ID</th>
                <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">Customer email</th>
                <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">Status</th>
                <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">Total</th>
                <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">Address</th>
              </tr>
            </thead>
            <tbody class="bg-white divide-y divide-gray-200">
              <% @completed_orders.each do |admin_order| %>
                <tr class="bg-gray-50 border-b hover:bg-gray-100">
                  <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-800 cursor-pointer">
                    <%= link_to admin_order.id, [:admin, admin_order], class: 'underline' %>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-800 cursor-pointer" onclick="window.location='<%= admin_order_path(admin_order) %>'">
                    <%= admin_order.customer_email %>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-800 cursor-pointer" onclick="window.location='<%= admin_order_path(admin_order) %>'">
                    <%= admin_order.status %>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-800 cursor-pointer" onclick="window.location='<%= admin_order_path(admin_order) %>'">
                    <%= admin_order.total %>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-800 cursor-pointer" onclick="window.location='<%= admin_order_path(admin_order) %>'">
                    <%= admin_order.address %>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-800">
                    <%= link_to icon('fas', 'pen-to-square'), edit_admin_order_path(admin_order), class: "rounded-lg py-3 px-3 bg-blue-600 text-white inline-block font-medium" %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/orders/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New order</h1>

  <%= render "form", admin_order: @admin_order %>

  <%= link_to "Back to orders", admin_orders_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/admin/orders/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @admin_order %>

    <%= link_to "Edit this order", edit_admin_order_path(@admin_order), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to orders", admin_orders_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this order", admin_order_path(@admin_order), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>