config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  authenticated :admin do
    root to: "admin#index", as: :admin_root
  end

  root "home#index"
  get "admin" => "admin#index"
  get "up" => "rails/health#show", as: :rails_health_check
  
  namespace :admin do
    resources :orders
    resources :categories
    resources :products do
      resources :stocks
    end
  end
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bytestore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="flex">
      <nav class="flex">
        <div class="w-64 p-4 hidden md:block h-screen bg-lightseagreen sticky top-0">
          <div class="flex">
            <%= image_tag 'logo.png', class: 'w-16'%>
            <h1 class="flex text-md w-full justify-center py-5 text-center text-gray-50 font-bold hidden md:block">Hi! <%=@current_admin.full_name%></h1>
          </div>
          <ul class="flex flex-col text-gray-50 py-5">
            <li>
              <%= link_to admin_path, class: "block px-4 py-2 hover:rounded hover:bg-gray-700" do %>
                <%= icon('fa-solid', 'gauge-high', class: 'mr-2') %>
                <span class="hidden md:inline-block">
                  Dashboard
                </span>
              <% end %>
            </li>
            <li>
              <%= link_to admin_products_path, class: "block px-4 py-2 hover:rounded hover:bg-gray-700" do %>
                <%= icon('fa-solid', 'cart-shopping', class: 'mr-2') %>
                <span class="hidden md:inline-block">
                  Products
                </span>
              <% end %>
            </li>
            <li>
              <%= link_to admin_categories_path, class: "block px-4 py-2 hover:rounded hover:bg-gray-700" do %>
                <%= icon('fa-solid', 'list', class: 'mr-2') %>
                <span class="hidden md:inline-block">
                  Categories
                </span>
              <% end %>
            </li>
            <li>
              <%= link_to admin_orders_path, class: "block px-4 py-2 hover:rounded hover:bg-gray-700" do %>
                <%= icon('fa-solid', 'truck-fast', class: 'mr-2') %>
                <span class="hidden md:inline-block">
                  Orders
                </span>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_admin_session_path, data: { "turbo-method": :delete, "turbo-confirm": "Are you sure you want to sign out?" }, class: "block px-4 py-2 hover:rounded hover:bg-gray-700" do %>
                <%= icon('fa-solid', 'sign-out', class: 'mr-2') %>
                <span class="hidden md:inline-block">
                  Sign Out
                </span>
              <% end %>
            </li>
          </ul>
        </div>
      </nav>
      <div class="p-4 w-full">
        <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bytestore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>